## HUDM 5199 - Spring 2022

## Yutong Shen, ys3453

## HW6 - March 23, 2022

### Session 8

### 2.1 Creating arrays from Existing Data

In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

**Multidimensional Arguments**

In [6]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

### 2.2 array Attributes

In [8]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [12]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

**Determining an array's Element Type**

In [13]:
integers.dtype

dtype('int64')

In [14]:
floats.dtype

dtype('float64')

**Determining an array's Dimensions**

In [15]:
integers.ndim

2

In [16]:
floats.ndim

1

In [17]:
integers.shape

(2, 3)

In [18]:
floats.shape

(5,)

**Determining an array's Number of Elements and Element Size**

In [19]:
integers.size

6

In [21]:
integers.itemsize

8

In [20]:
floats.size

5

In [22]:
floats.itemsize

8

**Iterating through a Multidimensional array's Elements**

In [23]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [25]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

### 2.3 Filling arrays with Specific Values

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

### 2.4 Creating arrays from Ranges

**Creating Integer Ranges with arange**

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [32]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

**Creating Floating-Point Ranges with linspace**

In [33]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**Reshaping an array**

In [34]:
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

**Displaying Large arrays**

In [37]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

### array Operators

In [42]:
numbers = np.arange(1, 6)

In [39]:
numbers

array([1, 2, 3, 4, 5])

In [40]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [41]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [43]:
numbers

array([1, 2, 3, 4, 5])

In [44]:
numbers + 10

array([11, 12, 13, 14, 15])

In [45]:
numbers

array([1, 2, 3, 4, 5])

In [46]:
numbers += 10
numbers

array([11, 12, 13, 14, 15])

**Arithmetic Operations Between arrays**

In [47]:
numbers

array([11, 12, 13, 14, 15])

In [48]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [49]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [50]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

**Comparing arrays**

In [51]:
numbers

array([11, 12, 13, 14, 15])

In [52]:
numbers >= 13

array([False, False,  True,  True,  True])

In [53]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [54]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [55]:
numbers == numbers2

array([False, False, False, False, False])

In [56]:
numbers == numbers

array([ True,  True,  True,  True,  True])

### 2.6 NumPy Calculation Methods

In [59]:
grades = np.array([[87, 96, 70], [100, 87, 90], 
                   [94, 77, 90], [100, 81, 82]])

In [60]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [61]:
grades.sum()

1054

In [62]:
grades.min()

70

In [63]:
grades.max()

100

In [64]:
grades.mean()

87.83333333333333

In [65]:
grades.std()

8.792357792739987

In [66]:
grades.var()

77.30555555555556

**Calculations by Row or Column**

In [67]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [68]:
grades.mean(axis=0)  #column-by-column

array([95.25, 85.25, 83.  ])

In [69]:
grades.mean(axis=1)  #row-by-row

array([84.33333333, 92.33333333, 87.        , 87.66666667])

### 2.7 Universal Functions

In [70]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [72]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [73]:
numbers2 = np.arange(1, 7) * 10

In [74]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [75]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

**Broadcasting with Universal Functions**

In [76]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [77]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [78]:
numbers3 = numbers2.reshape(2, 3)

In [79]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [80]:
numbers4 = np.array([2, 4, 6])
numbers4

array([2, 4, 6])

In [81]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

### 2.8 Indexing and Slicing 

In [82]:
grades = np.array([[87, 96, 70], [100, 87, 90], 
                   [94, 77, 90], [100, 81, 82]])

In [83]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [84]:
grades[0, 1]  #row 0, column 1

96

**Selecting a Subset of a Two-Dimensional array's Rows**

In [85]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [86]:
grades[1]

array([100,  87,  90])

In [87]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [88]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

**Selecting a Subset of a Two-Dimensional array's Columns**

In [89]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [90]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [91]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [93]:
grades[:, [0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

### 2.9 Views: Shallow Copies

In [94]:
numbers = np.arange(1, 6)

In [95]:
numbers

array([1, 2, 3, 4, 5])

In [96]:
numbers2 = numbers.view()

In [97]:
numbers2

array([1, 2, 3, 4, 5])

In [98]:
numbers[1] *= 10

In [99]:
numbers2

array([ 1, 20,  3,  4,  5])

In [100]:
numbers

array([ 1, 20,  3,  4,  5])

In [103]:
numbers2[1] /= 10

In [104]:
numbers

array([1, 2, 3, 4, 5])

In [105]:
numbers2

array([1, 2, 3, 4, 5])

### 2.10 Deep Copies

In [106]:
numbers = np.arange(1, 6)

In [107]:
numbers

array([1, 2, 3, 4, 5])

In [108]:
numbers2 = numbers.copy()

In [109]:
numbers2

array([1, 2, 3, 4, 5])

In [110]:
numbers[1] *= 10

In [111]:
numbers

array([ 1, 20,  3,  4,  5])

In [112]:
numbers2

array([1, 2, 3, 4, 5])

### Reshaping and Transposing

**reshape vs. resize**

In [113]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [114]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [115]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [116]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [117]:
grades.resize(1, 6)

In [118]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

**flatten vs. ravel**

In [119]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [120]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [122]:
flattened = grades.flatten()

In [123]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [124]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [125]:
flattened[0] = 100

In [126]:
flattened

array([100,  96,  70, 100,  87,  90])

In [127]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [129]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [130]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [131]:
raveled = grades.ravel()

In [132]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [133]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [134]:
raveled[0] = 100

In [135]:
raveled

array([100,  96,  70, 100,  87,  90])

In [136]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

**Transposing Rows and Columns**

In [137]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

**Horizontal and Vertical Stacking**

In [138]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [140]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])
grades2

array([[ 94,  77,  90],
       [100,  81,  82]])

In [141]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

### Textbook Exercises

**7.1**

In [147]:
arr1 = np.ones((2, 3))
print(arr1)
arr2 = np.zeros((3, 3))
print(arr2)
arr3 = np.full((2, 5), 7)
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


**7.2**

In [148]:
arr = np.arange(0, 4).reshape(2, 2)
arr

array([[0, 1],
       [2, 3]])

In [152]:
# a) Cube every element of the array.
arr1 = arr ** 3
arr1

array([[ 0,  1],
       [ 8, 27]])

In [153]:
# b) Add 7 to every element of the array.
arr2 = arr + 7
arr2

array([[ 7,  8],
       [ 9, 10]])

In [154]:
# c) Multiply every element of the array by 2.
arr3 = arr * 2
arr3

array([[0, 2],
       [4, 6]])

**7.3**

In [156]:
arr1 = np.arange(2, 19, 2).reshape(3, 3)
arr1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [158]:
arr2 = np.arange(9, 0, -1).reshape(3, 3)
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [159]:
arr3 = arr1 * arr2
arr3

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

**7.4**

In [160]:
arr = np.array([[2, 3, 5, 7, 11], [13, 17, 19, 23, 29]])
arr

array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29]])